Repository CruGlobal/ab_service_custom_reports, pull requests merged in 2024-10, with the labels that each got.

#134 *Fix refresh data when select a option
  reports/scripts/_team-rc-fy.js
Labels: patch

#135 Create due dates report for FCF.
  handlers/report.js
  reports/fcf-due-dates.js
  reports/templates/fcf-due-dates.ejs
Labels: feature :star2:, patch

#136 BugFix: Make sure person has visa attached before lookup
  reports/fcf-due-dates.js
Labels: bug :lady_beetle:, patch

#137 Check item exisits
  reports/fcf-due-dates.js
Labels: bug :lady_beetle:, patch

#138 increase limit so we do not miss any people
  reports/fcf-due-dates.js
  reports/templates/fcf-due-dates.ejs
Labels: patch
